import fs from "fs/promises";
import path from "path";
import type { SoftwareArtifact } from "@serverlab/shared";
import { logger } from "../../lib/logger.js";

export class ServerSoftwareInstaller {
  async install(input: {
    artifact: SoftwareArtifact;
    serverPath: string;
    eulaAccepted: boolean;
  }): Promise<void> {
    if (!input.eulaAccepted) {
      throw new Error("Minecraft EULA acceptance is required before creating a server");
    }

    const targetDir = path.resolve(input.serverPath);
    const targetJar = path.join(targetDir, "server.jar");
    await fs.mkdir(targetDir, { recursive: true });
    await fs.copyFile(input.artifact.cachedPath, targetJar);
    await fs.writeFile(
      path.join(targetDir, "eula.txt"),
      [
        "# Generated by ServerLab MC after the user accepted the Minecraft EULA.",
        "# https://aka.ms/MinecraftEULA",
        "eula=true",
        "",
      ].join("\n"),
      "utf8"
    );

    logger.info(
      {
        artifactId: input.artifact.id,
        provider: input.artifact.provider,
        version: input.artifact.minecraftVersion,
        build: input.artifact.buildId,
        targetDir,
      },
      "Server software installed"
    );
  }
}

export const serverSoftwareInstaller = new ServerSoftwareInstaller();
